[package]
name = "analog-config-program"
version = "1.8.2"
description = "Analog Config program"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-config-program"
edition = "2018"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0.137"
serde_derive = "1.0.103"
analog-sdk = { path = "../../sdk", version = "=1.8.2" }

[dev-dependencies]
analog-logger = { path = "../../logger", version = "=1.8.2" }

[lib]
crate-type = ["lib"]
name = "analog_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
