[package]
authors = ["Analog Maintainers <maintainers@analog.com>"]
description = "Blockchain, Rebuilt for Scale"
edition = "2018"
homepage = "https://analog.com/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/analog/testnet"
version = "1.8.2"

[workspace]

[dependencies]
tonic-build = "0.5.2"
