[package]
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
name = "analog-replica-node"
description = "Analog replication node"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-validator"

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.5"
log = "0.4.14"
rand = "0.7.0"
analog-clap-utils = { path = "../clap-utils", version = "=1.8.2" }
analog-download-utils = { path = "../download-utils", version = "=1.8.2" }
analog-genesis-utils = { path = "../genesis-utils", version = "=1.8.2" }
analog-gossip = { path = "../gossip", version = "=1.8.2" }
analog-ledger = { path = "../ledger", version = "=1.8.2" }
analog-logger = { path = "../logger", version = "=1.8.2" }
analog-net-utils = { path = "../net-utils", version = "=1.8.2" }
analog-rpc = { path = "../rpc", version = "=1.8.2" }
analog-replica-lib = { path = "../replica-lib", version = "=1.8.2" }
analog-runtime = { path = "../runtime", version = "=1.8.2" }
analog-sdk = { path = "../sdk", version = "=1.8.2" }
analog-streamer = { path = "../streamer", version = "=1.8.2" }
analog-version = { path = "../version", version = "=1.8.2" }
analog-validator = { path = "../validator", version = "=1.8.2" }

[dev-dependencies]
serial_test = "0.5.1"
analog-core = { path = "../core", version = "=1.8.2" }
analog-local-cluster = { path = "../local-cluster", version = "=1.8.2" }
tempfile = "3.2.0"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.5.1"
