[package]
name = "analog-bpf-loader-program"
version = "1.8.2"
description = "Analog BPF loader"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-bpf-loader-program"
edition = "2018"

[build-dependencies]
regex = "1.5.4"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
log = "0.4.14"
libsecp256k1 = "0.6.0"
analog-measure = { path = "../../measure", version = "=1.8.2" }
analog-program-runtime = { path = "../../program-runtime", version = "=1.8.2" }
analog-sdk = { path = "../../sdk", version = "=1.8.2" }
analog_rbpf = "=0.2.14"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
analog-runtime = { path = "../../runtime", version = "=1.8.2" }

[lib]
crate-type = ["lib"]
name = "analog_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
