[package]
name = "analog-stake-program"
version = "1.8.2"
description = "Analog Stake program"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-stake-program"
edition = "2018"

[dependencies]
bincode = "1.3.3"
log = "0.4.14"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.136"
serde_derive = "1.0.103"
analog-frozen-abi = { path = "../../frozen-abi", version = "=1.8.2" }
analog-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.8.2" }
analog-metrics = { path = "../../metrics", version = "=1.8.2" }
analog-sdk = { path = "../../sdk", version = "=1.8.2" }
analog-vote-program = { path = "../vote", version = "=1.8.2" }
analog-config-program = { path = "../config", version = "=1.8.2" }
thiserror = "1.0"

[dev-dependencies]
proptest = "1.0"
analog-logger = { path = "../../logger", version = "=1.8.2" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "analog_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
