[package]
name = "analog-noop-program"
version = "1.8.2"
description = "Analog Noop program"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-noop-program"
edition = "2018"

[dependencies]
log = "0.4.14"
analog-logger = { path = "../../logger", version = "=1.8.2" }
analog-sdk = { path = "../../sdk", version = "=1.8.2" }

[lib]
crate-type = ["lib", "cdylib"]
name = "analog_noop_program"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
