[package]
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
name = "analog-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-validator"
default-run = "analog-validator"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.14.1"
core_affinity = "0.5.10"
fd-lock = "3.0.0"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils= "18.0.0"
log = "0.4.14"
num_cpus = "1.13.0"
rand = "0.7.0"
analog-clap-utils = { path = "../clap-utils", version = "=1.8.2" }
analog-cli-config = { path = "../cli-config", version = "=1.8.2" }
analog-client = { path = "../client", version = "=1.8.2" }
analog-core = { path = "../core", version = "=1.8.2" }
analog-download-utils = { path = "../download-utils", version = "=1.8.2" }
analog-entry = { path = "../entry", version = "=1.8.2" }
analog-faucet = { path = "../faucet", version = "=1.8.2" }
analog-genesis-utils = { path = "../genesis-utils", version = "=1.8.2" }
analog-gossip = { path = "../gossip", version = "=1.8.2" }
analog-ledger = { path = "../ledger", version = "=1.8.2" }
analog-logger = { path = "../logger", version = "=1.8.2" }
analog-metrics = { path = "../metrics", version = "=1.8.2" }
analog-net-utils = { path = "../net-utils", version = "=1.8.2" }
analog-perf = { path = "../perf", version = "=1.8.2" }
analog-poh = { path = "../poh", version = "=1.8.2" }
analog-replica-lib = { path = "../replica-lib", version = "=1.8.2" }
analog-rpc = { path = "../rpc", version = "=1.8.2" }
analog-runtime = { path = "../runtime", version = "=1.8.2" }
analog-sdk = { path = "../sdk", version = "=1.8.2" }
analog-streamer = { path = "../streamer", version = "=1.8.2" }
analog-version = { path = "../version", version = "=1.8.2" }
analog-vote-program = { path = "../programs/vote", version = "=1.8.2" }
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {package = "tikv-jemallocator", version = "0.4.1"}

[target."cfg(unix)".dependencies]
libc = "0.2.102"
signal-hook = "0.2.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
