[package]
authors = ["Analog Maintainers <maintainers@analog.com>"]
edition = "2018"
name = "analog-log-analyzer"
description = "The analog cluster network analysis tool"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
publish = false

[dependencies]
byte-unit = "4.0.12"
clap = "2.33.1"
serde = "1.0.138"
serde_json = "1.0.68"
analog-logger = { path = "../logger", version = "=1.8.2" }
analog-version = { path = "../version", version = "=1.8.2" }

[[bin]]
name = "analog-log-analyzer"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
