[package]
name = "analog-bpf-rust-rand"
version = "1.8.2"
description = "Analog BPF test program written in Rust"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-bpf-rust-rand"
edition = "2018"

[dependencies]
getrandom = { version = "0.1.14", features = ["dummy"] }
rand = "0.7"
analog-program = { path = "../../../../sdk/program", version = "=1.8.2" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
