[package]
name = "analog-streamer"
version = "1.8.2"
description = "Analog Streamer"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-streamer"
edition = "2018"

[dependencies]
itertools = "0.10.1"
log = "0.4.14"
analog-metrics = { path = "../metrics", version = "=1.8.2" }
analog-sdk = { path = "../sdk", version = "=1.8.2" }
thiserror = "1.0"
analog-logger = { path = "../logger", version = "=1.8.2" }
libc = "0.2.102"
nix = "0.20.0"
analog-perf = { path = "../perf", version = "=1.8.2" }

[dev-dependencies]

[lib]
crate-type = ["lib"]
name = "analog_streamer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
