[package]
name = "analog-notifier"
version = "1.8.2"
description = "Analog Notifier"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-notifier"
edition = "2018"

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.4", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0"

[lib]
name = "analog_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
