[package]
name = "analog-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-stake-accounts"

[dependencies]
clap = "2.33.1"
analog-clap-utils = { path = "../clap-utils", version = "=1.8.2" }
analog-cli-config = { path = "../cli-config", version = "=1.8.2" }
analog-client = { path = "../client", version = "=1.8.2" }
analog-remote-wallet = { path = "../remote-wallet", version = "=1.8.2" }
analog-sdk = { path = "../sdk", version = "=1.8.2" }
analog-stake-program = { path = "../programs/stake", version = "=1.8.2" }

[dev-dependencies]
analog-runtime = { path = "../runtime", version = "=1.8.2" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
