[package]
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
name = "analog-watchtower"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-watchtower"

[dependencies]
clap = "2.33.1"
log = "0.4.14"
humantime = "2.0.1"
analog-clap-utils = { path = "../clap-utils", version = "=1.8.2" }
analog-cli-config = { path = "../cli-config", version = "=1.8.2" }
analog-cli-output = { path = "../cli-output", version = "=1.8.2" }
analog-client = { path = "../client", version = "=1.8.2" }
analog-logger = { path = "../logger", version = "=1.8.2" }
analog-metrics = { path = "../metrics", version = "=1.8.2" }
analog-notifier = { path = "../notifier", version = "=1.8.2" }
analog-sdk = { path = "../sdk", version = "=1.8.2" }
analog-version = { path = "../version", version = "=1.8.2" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
