[package]
name = "analog-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.14.1"
csv = "1.1.6"
ctrlc = { version = "3.1.9", features = ["termination"] }
indexmap = "1.7.0"
indicatif = "0.16.2"
pickledb = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
analog-account-decoder = { path = "../account-decoder", version = "=1.8.2" }
analog-clap-utils = { path = "../clap-utils", version = "=1.8.2" }
analog-cli-config = { path = "../cli-config", version = "=1.8.2" }
analog-client = { path = "../client", version = "=1.8.2" }
analog-remote-wallet = { path = "../remote-wallet", version = "=1.8.2" }
analog-sdk = { path = "../sdk", version = "=1.8.2" }
analog-transaction-status = { path = "../transaction-status", version = "=1.8.2" }
analog-version = { path = "../version", version = "=1.8.2" }
spl-associated-token-account-v1-0 = { package = "spl-associated-token-account", version = "=1.0.3" }
spl-token-v2-0 = { package = "spl-token", version = "=3.2.0", features = ["no-entrypoint"] }
tempfile = "3.2.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
analog-core = { path = "../core", version = "=1.8.2" }
analog-logger = { path = "../logger", version = "=1.8.2" }
analog-streamer = { path = "../streamer", version = "=1.8.2" }
