[package]
name = "analog-secp256k1-program"
description = "Analog Secp256k1 program"
version = "1.8.2"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-secp256k1-program"
repository = "https://github.com/analog/testnet"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
analog-sdk = { path = "../../sdk", version = "=1.8.2" }

[dev-dependencies]
bincode = "1.3.3"
libsecp256k1 = "0.6.0"
rand = "0.7.0"
analog-logger = { path = "../../logger", version = "=1.8.2" }

[lib]
crate-type = ["lib"]
name = "analog_secp256k1_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
