[package]
name = "analog-cargo-test-bpf"
version = "1.8.2"
description = "Execute all unit and integration tests after building with the Analog BPF SDK"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
homepage = "https://analog.com/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.14.0"

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
