[package]
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
name = "analog-cli-config"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-cli-config"

[dependencies]
dirs-next = "2.0.0"
lazy_static = "1.4.0"
serde = "1.0.145"
serde_derive = "1.0.103"
serde_yaml = "0.8.21"
url = "2.2.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
