[package]
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
name = "analog-install"
description = "The analog cluster software installer"
version = "1.8.2"
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-install"

[dependencies]
atty = "0.2.11"
bincode = "1.3.3"
bzip2 = "0.4.3"
chrono = { version = "0.4.11", features = ["serde"] }
clap = { version = "2.33.1" }
console = "0.14.1"
ctrlc = { version = "3.1.9", features = ["termination"] }
dirs-next = "2.0.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
nix = "0.20.0"
reqwest = { version = "0.11.4", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.8.21"
analog-clap-utils = { path = "../clap-utils", version = "=1.8.2" }
analog-client = { path = "../client", version = "=1.8.2" }
analog-config-program = { path = "../programs/config", version = "=1.8.2" }
analog-logger = { path = "../logger", version = "=1.8.2" }
analog-sdk = { path = "../sdk", version = "=1.8.2" }
analog-version = { path = "../version", version = "=1.8.2" }
semver = "1.0.4"
tar = "0.4.37"
tempfile = "3.2.0"
url = "2.2.2"

[target."cfg(windows)".dependencies]
winapi = "0.3.8"
winreg = "0.10"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
