[package]
name = "analog-storage-bigtable"
version = "1.8.2"
description = "Analog Storage BigTable"
authors = ["Analog Maintainers <maintainers@analog.com>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-storage-bigtable"
edition = "2018"

[dependencies]
backoff = { version = "0.3.0", features = ["tokio"] }
bincode = "1.3.3"
bzip2 = "0.4.3"
enum-iterator = "0.7.0"
flate2 = "1.0.22"
goauth = "0.10.0"
log = "0.4.14"
prost = "0.8.0"
prost-types = "0.8.0"
serde = "1.0.141"
serde_derive = "1.0.103"
smpl_jwt = "0.6.0"
analog-sdk = { path = "../sdk", version = "=1.8.2" }
analog-storage-proto = { path = "../storage-proto", version = "=1.8.2" }
analog-transaction-status = { path = "../transaction-status", version = "=1.8.2" }
thiserror = "1.0"
tonic = { version = "0.5.2", features = ["tls", "transport"] }
zstd = "0.9.0"

[lib]
crate-type = ["lib"]
name = "analog_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
