[package]
name = "analog-bpf-rust-sysvar"
version = "1.8.2"
description = "Analog BPF test program written in Rust"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog/testnet"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-bpf-rust-sysvar"
edition = "2018"

[dependencies]
analog-program = { path = "../../../../sdk/program", version = "=1.8.2" }

[dev-dependencies]
analog-program-test = { path = "../../../../program-test", version = "=1.8.2" }
analog-sdk = { path = "../../../../sdk", version = "=1.8.2" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
