[package]
name = "analog-bpf-programs"
description = "Blockchain, Rebuilt for Scale"
version = "1.8.2"
documentation = "https://docs.rs/analog"
homepage = "https://analog.com/"
readme = "README.md"
repository = "https://github.com/analog/testnet"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
bpf_c = []
bpf_rust = []

[build-dependencies]
walkdir = "2"

[dependencies]
bincode = "1.1.4"
byteorder = "1.3.2"
elf = "0.0.10"
itertools = "0.10.1"
log = "0.4.11"
miow = "0.3.6"
net2 = "0.2.37"
analog-bpf-loader-program = { path = "../bpf_loader", version = "=1.8.2" }
analog-cli-output = { path = "../../cli-output", version = "=1.8.2" }
analog-logger = { path = "../../logger", version = "=1.8.2" }
analog-measure = { path = "../../measure", version = "=1.8.2" }
solana_rbpf = "=0.2.14"
analog-runtime = { path = "../../runtime", version = "=1.8.2" }
analog-sdk = { path = "../../sdk", version = "=1.8.2" }
analog-transaction-status = { path = "../../transaction-status", version = "=1.8.2" }
analog-account-decoder = { path = "../../account-decoder", version = "=1.8.2" }


[[bench]]
name = "bpf_loader"

[workspace]
members = [
    "rust/128bit",
    "rust/128bit_dep",
    "rust/alloc",
    "rust/call_depth",
    "rust/caller_access",
    "rust/custom_heap",
    "rust/dep_crate",
    "rust/deprecated_loader",
    "rust/dup_accounts",
    "rust/error_handling",
    "rust/log_data",
    "rust/external_spend",
    "rust/finalize",
    "rust/instruction_introspection",
    "rust/invoke",
    "rust/invoke_and_error",
    "rust/invoke_and_ok",
    "rust/invoke_and_return",
    "rust/invoked",
    "rust/iter",
    "rust/many_args",
    "rust/many_args_dep",
    "rust/mem",
    "rust/membuiltins",
    "rust/noop",
    "rust/panic",
    "rust/param_passing",
    "rust/param_passing_dep",
    "rust/rand",
    "rust/ro_modify",
    "rust/ro_account_modify",
    "rust/sanity",
    "rust/secp256k1_recover",
    "rust/sha",
    "rust/spoof1",
    "rust/spoof1_system",
    "rust/sysvar",
    "rust/upgradeable",
    "rust/upgraded",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
