[package]
name = "analog-poh"
version = "1.9.0"
description = "Analog PoH"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-poh"
edition = "2018"

[dependencies]
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
log = "0.4.14"
analog-entry = { path = "../entry", version = "=1.9.0" }
analog-ledger = { path = "../ledger", version = "=1.9.0" }
analog-measure = { path = "../measure", version = "=1.9.0" }
analog-metrics = { path = "../metrics", version = "=1.9.0" }
analog-runtime = { path = "../runtime", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }
analog-sys-tuner = { path = "../sys-tuner", version = "=1.9.0" }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
matches = "0.1.9"
rand = "0.7.0"
analog-logger = { path = "../logger", version = "=1.9.0" }
analog-perf = { path = "../perf", version = "=1.9.0" }

[lib]
crate-type = ["lib"]
name = "analog_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
